### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by dpo** [CiDAMO/AugLag.jl#3]
I haven't yet tried to run your code but here are a few comments and suggestions from a first reading:
- [x] `obj()` [allocates](https://github.com/Egmara/AugLag.jl/blob/master/src/AugLagModel.jl#L36) a new vector every time for the constraint values; why not preallocate a vector of size `ncon` inside the `AugLagModel` and use `cons!()` instead?
- [x] `obj()` and `grad()` both evaluate the constraints, so you probably want to implement `objgrad!()` and save one constraint evaluation;
- [x] we should probably implement memoization so `grad()` does not reevaluate the constraints where `obj()` just evaluated them;
- [x] ~~`hess_structure!()` doesn't look right; the *J'J* term could fill in the Hessian substantially. It's not hard to figure out the sparsity pattern of *J'J* from that of *J*;~~
- [x] ~~`hess_coord!()` doesn't look right either. Also it should call `hess_coord!()` and `jac_coord()` on the original `nlp`;~~
- [x] there is no need to implement `grad()`, `hess()`, `hess_structure()`, `hess_coord()` and `hprod()` because you already implement the `!` version of those methods;
- [x] there is no need to implement `hess_op()` and `hess_op!()` because you already implement `hprod!()`.

Note that because you use TRON as subproblem solver, you don't need `hess_structure!()` or `hess_coord!()`. You could leave those out for now.

**Comment by Egmara** [comment]
- Unnecessary functions have been removed;

- here #15 I used the pre-allocation for constraint values in `AugLagModel ` and `cons!()` instead `cons() `in `obj()`, `grad!()` and `hprod!() `functions. But, I dont implement memoization yet;

- The `objgrad!()` function for `AugLagModel `is not required in the inner solver (tron), do I need to implement this?

**Comment by dpo** [comment]
Is it feasible to modify TRON to use `objgrad()`? It seems like we would save quite a bit here.

**Comment by abelsiqueira** [comment]
I've created https://github.com/JuliaSmoothOptimizers/JSOSolvers.jl/issues/30 to handle that.
