### ISSUE TITLE
Treat inequalities with slack

### ISSUE THREAD

**Issue by abelsiqueira** [CiDAMO/AugLag.jl#8]

**Comment by Egmara** [comment]
#12 it runs the tests with inequality problems, but the second and the last do not pass because the solutions found are not the same as the ones provided in the test. I checked the kkt system and the solutions found are stationary. I think the solutions are correct. I'm not sure.

**Comment by dpo** [comment]
You could initialize IPOPT from those solutions and see if it agrees.

**Comment by Egmara** [comment]
Thanks for the suggestion. I checked it. The solutions found by me and ipopt are the same.
